ConfigureConsole();

//FILTERING AND SORTING SEQUENCES
//FilterAndSort();

//JOINING, GROUPING, AND LOOKUPS
//JOINING SEQUENCES
//JoinCatagoriesAndProducts();

//GROUP-JOINING SEQUENCES 
//GroupJoinCategoriesAndProducts();

//GROUPING FOR LOOKUPS
ProductsLookUp();

//AGGREGATING AND PAGING SEQUENCES